# Feildmaster is the actual mastermind behind this, as usual. :P

name: Daily Login
on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * *" # About 1 hour before reset
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Node setup
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - name: Install
        run: npm install --production
      - name: Update
        env:
          LOGIN_CREDENTIALS: ${{ secrets.LOGIN_CREDENTIALS }}
        run: npm start "$LOGIN_CREDENTIALS"
      - name: Commit
        uses: EndBug/add-and-commit@v5
        with:
          author_name: Trackbot
          message: "chore: Daily Login"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
